correct timing when it is calendar-based spending
Merck/gsDesign2 pull request #383
Opened 2024-04-26 19:43 UTC by LittleBeannie

2024-04-29 15:19 UTC, jdblischak requested changes
Since you are changing the behavior of `to_integer()`, could you please bump the build number to 1.1.2.3?

https://github.com/Merck/gsDesign2/blob/eb62b764b48f1e9951751db1a6b630d700d78ff8/DESCRIPTION#L3

Also, I recommend converting the example in https://github.com/Merck/gsDesign2/issues/382 to a test so that we can be confident that the error remains fixed in the future.

2024-04-29 15:20 UTC, LittleBeannie commented
> Since you are changing the behavior of `to_integer()`, could you please bump the build number to 1.1.2.3?
> 
> https://github.com/Merck/gsDesign2/blob/eb62b764b48f1e9951751db1a6b630d700d78ff8/DESCRIPTION#L3
> 
> Also, I recommend converting the example in #382 to a test so that we can be confident that the error remains fixed in the future.

Good suggestions, agreed! I will get your comments addressed in another commit.

2024-04-29 17:35 UTC, jdblischak approved these changes

2024-04-30 02:47 UTC, nanxstats approved these changes
(I simply ran `styler:::style_active_file()` on the change files to fix the code style problems.)

2024-04-30 02:47 UTC, merged