Ahr blinded test
Merck/gsDesign2 pull request #435
Opened 2024-07-09 17:03 UTC by DMuriuki

Adding test file for ahr_blinded function

2024-07-18 15:19 UTC, nanxstats commented
Focus on `tests/testthat/test-independent-ahr_blinded.R`

2024-08-02 18:10 UTC, nanxstats requested changes
Hey @DMuriuki I rebased your PR so the merge conflicts are now resolved. Please take a look at this failing test and make necessary updates:

```
  ── Failure ('test-independent-ahr_blinded.R:17:3'): Piecewise model hr and intervals must be aligned ──
  `ahr_blinded(hr = c(1, 3), intervals = c(3, 4))` did not throw an error.
```

You can use

```
git clone -b ahr-blinded-test https://github.com/Merck/gsDesign2.git
```

to clone the latest version of this branch to local, install, fix the test, and push.

2024-08-20 16:39 UTC, nanxstats reviewed
@LittleBeannie This PR is ready for review. 90% code coverage for `ahr_blinded()`.

2024-08-22 18:28 UTC, LittleBeannie requested changes
Thanks, @DMuriuki and @nanxstats for the testing! Following, please find my comments.

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  # Test 1: Correct fitting of survival data into piecewise exponential model
I am wondering if "Test 1" is informative or not... it looks like it does not compare the output of `ahr_blinded` with some double-programming/independent programming results...

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  # Test 2: Hazard ratio vector is correctly extended
Echo with my comments to "Test 1".

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  # Test 3: Blinded AHR (theta) is computed correctly
Echo with my comments to "Test 1".

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  theta <- -sum(log(hr[1:nx]) * event) / sum(event)
It looks like the calculation of `theta` is exactly the same as what we have in https://github.com/Merck/gsDesign2/blob/main/R/ahr_blinded.R#L109. So, I am wondering if it is a validated independent testing or not.

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  # Test 4: Information adjustment (q_e) is computed correctly
Echo with my comment to "Test 1".

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  hr_large <- c(10, 20, 30)
HR is always a number between 0 and 1. So it is not statistically meaningful to have `hr_large = c(10, 20, 30)`.

2024-08-22 18:28 UTC, LittleBeannie commented on tests/testthat/test-independent-ahr_blinded.R
> +  expect_equal(q_e, 1, tolerance = 0.01)
Echo with my comments to "Test 1".

2024-08-25 21:49 UTC, nanxstats commented
@LittleBeannie Great, I've just removed the non-informative and unrealistic test cases.

2024-08-29 13:10 UTC, LittleBeannie approved these changes
Thanks a lot, @DMuriuki and @nanxstats !

2024-08-29 13:10 UTC, merged